import { NextResponse } from 'next/server';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  // Return a simple HTML report that can be converted to PDF via window.print()
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Inspection Report - ${id}</title>
  <style>
    body { font-family: 'Times New Roman', serif; max-width: 800px; margin: 0 auto; padding: 40px; }
    h1 { text-align: center; font-size: 18px; border-bottom: 2px solid #0B2545; padding-bottom: 12px; }
    .header { text-align: center; margin-bottom: 24px; }
    .field { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #E5E7EB; }
    .section { margin-top: 24px; }
    .section h2 { font-size: 14px; background: #0B2545; color: #fff; padding: 6px 12px; }
    .certificate { border: 2px solid #D4AF37; padding: 16px; margin-top: 24px; background: #FAFAF5; }
  </style>
</head>
<body>
  <div class="header">
    <p style="font-size: 12px; letter-spacing: 2px;">GOVERNMENT OF INDIA</p>
    <h1>LEGAL METROLOGY INSPECTION REPORT</h1>
    <p>Dossier Reference: <strong>${id}</strong></p>
  </div>
  <p style="text-align: center; color: #666;">
    This report was generated by CompliScan AI. Use Ctrl+P or the Export PDF button to save.
  </p>
  <div class="certificate">
    <h3 style="color: #D4AF37;">Section 63 — Bharatiya Sakshya Adhiniyam, 2023</h3>
    <p style="font-size: 12px;">Digital Evidence Certificate — This electronic record meets the requirements of Section 63(4) for judicial admissibility.</p>
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html' },
  });
}
